### ISSUE TITLE
No está el Código Fuente

### ISSUE THREAD

**Issue by beto-bit** [MarccosGodoy/spam-bot#1]
Vengo de YouTube. En la carpeta solo se encuentra el compilado de la aplicación, la cual debería estar en **Releases** y el Source Code debería estar incluido en el repositorio.

**Comment by MarccosGodoy** [comment]
Hola! A mi si me figura que esta el codigo, te referis a esto?
https://prnt.sc/zek8lj

Y tenes razon, deberia poner la aplicacion compilada en Releases, gracias por el aviso.
Si por algun motivo no podes agarrar el codigo fuente, fijate que en el video hay un link de descarga de drive, en el cual deberia estar! avisame cualquier cosa, perdona la demora :)

**Comment by beto-bit** [comment]
Perdón, mi error. Gracias por hacermelo  notar. Muy amable de tu parte.
